
#ifndef __NEOHID_H
#define __NEOHID_H


#define AK_ESCAPE        0x01
#define AK_1             0x02
#define AK_2             0x03
#define AK_3             0x04
#define AK_4             0x05
#define AK_5             0x06
#define AK_6             0x07
#define AK_7             0x08
#define AK_8             0x09
#define AK_9             0x0A
#define AK_0             0x0B
#define AK_MINUS         0x0C
#define AK_EQUALS        0x0D
#define AK_BACKSPACE     0x0E
#define AK_TAB           0x0F
#define AK_Q             0x10
#define AK_W             0x11
#define AK_E             0x12
#define AK_R             0x13
#define AK_T             0x14
#define AK_Y             0x15
#define AK_U             0x16
#define AK_I             0x17
#define AK_O             0x18
#define AK_P             0x19
#define AK_LEFT_BRACKET  0x1A
#define AK_RIGHT_BRACKET 0x1B
#define AK_RETURN        0x1C
#define AK_LEFT_CONTROL  0x1D
#define AK_A             0x1E
#define AK_S             0x1F
#define AK_D             0x20
#define AK_F             0x21
#define AK_G             0x22
#define AK_H             0x23
#define AK_J             0x24
#define AK_K             0x25
#define AK_L             0x26
#define AK_SEMICOLON     0x27
#define AK_QUOTE         0x28
#define AK_BACK_TICK     0x29
#define AK_LEFT_SHIFT    0x2A
#define AK_BACKSLASH     0x2B
#define AK_Z             0x2C
#define AK_X             0x2D
#define AK_C             0x2E
#define AK_V             0x2F
#define AK_B             0x30
#define AK_N             0x31
#define AK_M             0x32
#define AK_COMMA         0x33
#define AK_PERIOD        0x34
#define AK_SLASH         0x35
#define AK_RIGHT_SHIFT   0x36
#define AK_KP_TIMES      0x37
#define AK_LEFT_ALT      0x38
#define AK_SPACE         0x39
#define AK_CAPSLOCK      0x3A
#define AK_F1            0x3B
#define AK_F2            0x3C
#define AK_F3            0x3D
#define AK_F4            0x3E
#define AK_F5            0x3F
#define AK_F6            0x40
#define AK_F7            0x41
#define AK_F8            0x42
#define AK_F9            0x43
#define AK_F10           0x44
#define AK_NUMLOCK       0x45
#define AK_SCROLL_LOCK   0x46
#define AK_KP_7          0x47
#define AK_KP_8          0x48
#define AK_KP_9          0x49
#define AK_KP_MINUS      0x4A
#define AK_KP_4          0x4B
#define AK_KP_5          0x4C
#define AK_KP_6          0x4D
#define AK_KP_PLUS       0x4E
#define AK_KP_1          0x4F
#define AK_KP_2          0x50
#define AK_KP_3          0x51
#define AK_KP_0          0x53
#define AK_KP_F11        0x57
#define AK_KP_F12        0x58

#endif // __NEOHID_H
